spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**
        - id: patient-service
          uri: http://localhost:8082
          predicates:
            - Path=/patient/**
        - id: record-service
          uri: http://localhost:8083
          predicates:
            - Path=/record/**
  data:
    mongodb:
      uri: mongodb://localhost:27017/hospitalDB

server:
  port: 8080
